Feature/task fc0a layout page login
inclusive-pet/inclusive-pet-mobile pull request #18
Opened 2022-08-16 03:29 UTC by brenolyES

<h1 align="center">🐾 Inclusive Pet Mobile</h1>

# Descrição

Layout da tela de login parcialmente finalizado, componentes relativos a tela de login foram feitos.

Correções # (issue)

## Tipo de mudança / alteração deste pull request

Por favor, marque as opções que são relevantes.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Hotfix (non-breaking change which fixes a critical production issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Como as alterações deste pull request foram testadas?

Descreva os testes que você executou para verificar suas alterações.

- [ ] Test Endpoints (e2e)
- [ ] Test App Services (unit)
- [ ] Test Domain Services (unit)

**Configuração dos Testes**:

- OS Name:
- OS Version:
- Hardware:
- Toolchain:
- SDK:

# Preencha a checklist a seguir para termos algumas informações adicionais:

- [ ] Meu código segue as diretrizes de estilo deste projeto.
- [ ] Realizei uma auto-revisão do meu próprio código.
- [ ] Eu comentei meu código, particularmente em áreas difíceis de entender.
- [ ] Fiz as alterações correspondentes na documentação.
- [ ] Minhas alterações não geram novos warnings.
- [ ] Adicionei testes que comprovam que minha correção é eficaz ou que meu recurso funciona.
- [ ] Testes unitários novos e existentes foram atualizados e estão funcionando.
- [ ] Quaisquer alterações dependentes foram mescladas e publicadas em módulos downstream.

2022-08-16 13:52 UTC, tonicprism requested changes
Deixei alguns comentários, para algumas melhorias, mas o código está show! Parabéns, @brenolyES!

2022-08-16 13:52 UTC, tonicprism commented on package.json
> +    "react-native-text-link": "^1.0.0",
Porque que você precisa dessa lib?

2022-08-16 13:52 UTC, tonicprism commented on source/core/components/TextInput/index.tsx
> +  const hasRightIcon = !!rightIconName
Substitui o `!!` por um `Boolean`, por favor.

2022-08-16 13:52 UTC, tonicprism commented on source/core/components/TextInput/index.tsx
> +  const defaultStyles = styles(isWhite, theme, hasRightIcon)
Substitui esse styles por um styled-components, visto que já está configurado e instalado.

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/components/AuthenticationGradient/index.tsx
> +      {props.children}
Pega esse children de dentro do props por desestruturação e não desse jeito, por favor.

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/components/AuthenticationGradient/styles.ts
> +export const styles = StyleSheet.create({
Utiliza styled-components aqui, por favor.

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/components/AuthenticationGradient/types/index.d.ts
> +  children: React.ReactChild
Utiliza `React.ReactNode` em vez de `React.ReactChild`, por favor, Por que o `ReactChild` infere que só irá existir um componente filho e não vários (por isso o 'child' - 'filho').

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/components/Hyperlink/index.tsx
> +      textStyle={styleText || styles(theme).styleText}
Em vez de || (logical OR) utiliza o ?? (nullish coalescing) aqui, por favor. Pois, o || só é importante para verificação de valores que não são 'verdadeiros'. Já nesse caso, você somente quer verificar se o primeiro valor é undefined e caso seja ele irá pegar o segundo valor e essa é de fato a função do ??.

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/components/Hyperlink/styles.ts
> +export const styles = (theme: Omit<DefaultTheme, 'fonts'>) =>
Transforma esse style em styled-components, por favor.

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/components/Hyperlink/styles.ts
> +      fontSize: 16,
Utiliza o tamanho de fontes definido no tema, por favor.

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/screens/LoginScreen/index.tsx
> +          isWhite={true}
```suggestion
          isWhite
```
Quando uma property é true não precisa dizer que ela é igual a true, só precisa definir ela.

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/screens/LoginScreen/index.tsx
> +          isWhite={true}
Quando uma property é true não precisa dizer que ela é igual a true, só precisa definir ela.

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/screens/LoginScreen/index.tsx
> +          isPassword={true}
Quando uma property é true não precisa dizer que ela é igual a true, só precisa definir ela.

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/screens/LoginScreen/index.tsx
> +            onPressText={() =>
Tirá essa chamada de método do render, por favor, e cria um método lá em cima. O nome pode ser: `onPressForgotPasswordTextGoToRecoveryPasswordScreen`

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/screens/LoginScreen/index.tsx
> +          onPress={() =>
Tirá essa chamada de método do render, por favor, e cria um método lá em cima

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/screens/LoginScreen/index.tsx
> +          onPress={() =>
Tirá essa chamada de método do render, por favor, e cria um método lá em cima

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/screens/LoginScreen/index.tsx
> +          isWhite={true}
Quando uma property é true não precisa dizer que ela é igual a true, só precisa definir ela.

2022-08-16 13:52 UTC, tonicprism commented on source/modules/authentication/screens/LoginScreen/index.tsx
> +          isOutline={true}
Quando uma property é true não precisa dizer que ela é igual a true, só precisa definir ela.

2022-08-16 13:54 UTC, tonicprism commented on package.json
> +    "react-native-text-link": "^1.0.0",
Visto que a única coisa que a lib faz é deixar o texto azul e tornar ele clicável, você consegue fazer isso na mão sem precisar de uma lib para isso.
O próprio componente `Text` do React Native, possui um método `onPress` (https://reactnative.dev/docs/text#onpress) e acredito que a lib react native elements tenha um tipo de botão texto.

2022-08-17 13:19 UTC, tonicprism commented on source/core/components/TextInput/index.tsx
> +  const hasRightIcon = !!rightIconName
```suggestion
  const hasRightIcon = Boolean(rightIconName)
```

2022-08-17 15:41 UTC, tonicprism commented on source/core/components/TextInput/index.tsx
> +      marginRight: !hasRightIcon ? 25 : 0,
Esse margeamento deve ser pego diretamente do tema.

2022-08-17 17:43 UTC, tonicprism commented on source/modules/authentication/components/AuthenticationGradient/index.tsx
> +      {props.children}
@brenolyES Ainda falta esse ponto aqui.

2022-08-17 17:43 UTC, tonicprism commented on source/modules/authentication/components/AuthenticationGradient/styles.ts
> +export const styles = StyleSheet.create({
@brenolyES Ainda falta esse ponto aqui.

2022-08-17 17:43 UTC, tonicprism commented on source/modules/authentication/components/AuthenticationGradient/styles.ts
> +import { LinearGradient as _LinearGradient } from 'expo-linear-gradient'
```suggestion
import { LinearGradient as ExpoLinearGradient } from 'expo-linear-gradient'
```

2022-08-17 17:43 UTC, tonicprism commented on source/modules/authentication/components/AuthenticationGradient/styles.ts
> +export const LinearGradient = styled(_LinearGradient)`
```suggestion
export const LinearGradient = styled(ExpoLinearGradient)`
```

2022-08-17 17:47 UTC, brenolyES commented on source/core/components/TextInput/index.tsx
> +      marginRight: !hasRightIcon ? 25 : 0,
o problema é que no tema nao tem o tamanho correto pra esse caso em especifico, mas vou mudar para outra abordagem diferente nesse trecho ai, daqui pra noite mando o commit.

2022-08-17 17:56 UTC, merged