Feature/task 5ea5 create layout card feed component
inclusive-pet/inclusive-pet-mobile pull request #30
Opened 2022-08-31 00:45 UTC by KelvinVasconcelos

<h1 align="center">🐾 Inclusive Pet Mobile</h1>

# Descrição

Criado componente para utilizar nas postagens do feed.

Correções # (issue)

## Tipo de mudança / alteração deste pull request

Por favor, marque as opções que são relevantes.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Hotfix (non-breaking change which fixes a critical production issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Como as alterações deste pull request foram testadas?

Descreva os testes que você executou para verificar suas alterações.

- [ ] Test Endpoints (e2e)
- [ ] Test App Services (unit)
- [ ] Test Domain Services (unit)

**Configuração dos Testes**:

- OS Name:
- OS Version:
- Hardware:
- Toolchain:
- SDK:

# Preencha a checklist a seguir para termos algumas informações adicionais:

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Realizei uma auto-revisão do meu próprio código.
- [x] Eu comentei meu código, particularmente em áreas difíceis de entender.
- [x] Fiz as alterações correspondentes na documentação.
- [ ] Minhas alterações não geram novos warnings.
- [ ] Adicionei testes que comprovam que minha correção é eficaz ou que meu recurso funciona.
- [ ] Testes unitários novos e existentes foram atualizados e estão funcionando.
- [ ] Quaisquer alterações dependentes foram mescladas e publicadas em módulos downstream.

2022-08-31 02:53 UTC, tonicprism requested changes

2022-08-31 02:53 UTC, tonicprism commented on source/modules/home/components/FeedPost/index.tsx
> +    if (type === 'pet_lost') {
Em vez desses ifs utiliza um object literals do javascript e define um tipo pra esse `type`, em vez de ser uma string.

2022-08-31 02:53 UTC, tonicprism commented on source/modules/home/components/FeedPost/index.tsx
> +          color={Theme.colors.primary}
Em vez de pegar a color diretamente da constante `Theme`, recupera ela utilizando o hook `useTheme` do serviço do styled component no módulo core da aplicação;

2022-08-31 02:53 UTC, tonicprism commented on source/modules/home/components/FeedPost/styles.ts
> +  flex: 8;
Por que você precisa utilizar esse flex: 8? Um flex: 2 não funcionaria não?

2022-08-31 02:53 UTC, tonicprism commented on source/modules/home/components/FeedPost/styles.ts
> +  padding: 4px;
Utiliza esse padding do tema, para o padding do aplicativo permanecer padronizado.

2022-08-31 02:53 UTC, tonicprism commented on source/modules/home/components/FeedPost/styles.ts
> +  margin: 6px 0px 0px 8px;
Utiliza esse margin do tema, para o margin do aplicativo permanecer padronizado.

2022-08-31 02:53 UTC, tonicprism commented on source/modules/home/components/FeedPost/styles.ts
> +  font-family: ${({ theme }) => theme.fonts.variations.Montserrat_400Regular};
Você não precisa definir a font-family aqui no estilo. Você pode utilizar o componente `Text ` do app e la no render escolher a propriedade `fontFamily`.

2022-08-31 02:53 UTC, tonicprism commented on source/modules/home/components/FeedPost/styles.ts
> +  font-family: ${({ theme }) => theme.fonts.variations.Montserrat_400Regular};
Você não precisa definir a font-family aqui no estilo. Você pode utilizar o componente `Text ` do app e la no render escolher a propriedade `fontFamily`.

2022-08-31 02:53 UTC, tonicprism commented on source/modules/home/components/FeedPost/types/index.d.ts
> +    full_name: string
Remove esse snake case aqui, por favor e utiliza camel case.

2022-08-31 02:53 UTC, tonicprism commented on source/modules/home/screens/FeedScreen/index.tsx
>        <Button title="Deslogar" onPress={() => doLogout()} />
aqui você pode chamar o doLogout diretamente assim:
```suggestion
      <Button title="Deslogar" onPress={doLogout} />
```

2022-08-31 02:54 UTC, tonicprism commented on source/modules/home/components/FeedPost/index.tsx
> +    if (type === 'pet_lost') {
Dá uma olhada no componente `Toast`, lá eu utilizo o object literals para fazer algo semelhante.

2022-08-31 10:51 UTC, helainelins commented
Parabéns pelo trabalho pessoal! Emocionante ver a evolução em 2 anos de trabalho com vcs!

2022-09-02 02:45 UTC, tonicprism approved these changes

2022-09-02 03:17 UTC, merged